version: '3.8'

services:
  decrossword-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: abdennasserbentaleb/decrossword:1.0.0
    container_name: decrossword-ui
    ports:
      - "8080:8080"
    restart: always
    security_opt:
      - no-new-privileges:true
    read_only: true
    cap_drop:
      - ALL
    # Since we are dropping privileges and setting read_only root, Nginx needs writable tmp paths
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health/liveness || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
